"""Fresh start

Revision ID: 06e5f97e2bad
Revises: 
Create Date: 2026-03-29 18:03:50.587133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06e5f97e2bad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gaming_facilities',
    sa.Column('serial_no', sa.Integer(), nullable=False),
    sa.Column('equipment_name', sa.String(length=200), nullable=False),
    sa.Column('availability_status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('serial_no')
    )
    op.create_table('hostel',
    sa.Column('hostel_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('no_of_rooms', sa.Integer(), nullable=False),
    sa.Column('hostel_contact', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('hostel_id')
    )
    op.create_table('staff_members',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_no', sa.String(length=20), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('staff_id')
    )
    with op.batch_alter_table('staff_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_members_email'), ['email'], unique=True)

    op.create_table('student',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('student_id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_email'), ['email'], unique=True)

    op.create_table('attendance',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LEAVE', name='attendancestatus'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('student_id', 'date')
    )
    op.create_table('complaint',
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_members.staff_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('complaint_id')
    )
    op.create_table('equipment_usage',
    sa.Column('usage_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('serial_no', sa.Integer(), nullable=False),
    sa.Column('issued_time', sa.DateTime(), nullable=False),
    sa.Column('submission_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['serial_no'], ['gaming_facilities.serial_no'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('usage_id')
    )
    op.create_table('laundry',
    sa.Column('laundry_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('items', sa.Text(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('laundry_id')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostel_id', sa.Integer(), nullable=False),
    sa.Column('room_no', sa.String(length=50), nullable=False),
    sa.Column('room_type', sa.Enum('AC', 'NON_AC', name='roomtype'), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostel.hostel_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostel_id', 'room_no', name='uq_room_hostel_room_no')
    )
    op.create_table('task_allocation',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('assigned_date', sa.Date(), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_members.staff_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('warden',
    sa.Column('warden_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('contact_no', sa.String(length=20), nullable=False),
    sa.Column('hostel_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostel.hostel_id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_members.staff_id'], ),
    sa.PrimaryKeyConstraint('warden_id')
    )
    op.create_table('ac_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chief_warden',
    sa.Column('warden_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['warden_id'], ['warden.warden_id'], ),
    sa.PrimaryKeyConstraint('warden_id')
    )
    op.create_table('feedback',
    sa.Column('serial_no', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaint.complaint_id'], ),
    sa.PrimaryKeyConstraint('complaint_id', 'serial_no')
    )
    op.create_table('non_ac_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_allocation',
    sa.Column('alloc_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('alloc_date', sa.Date(), nullable=False),
    sa.Column('vacate_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('alloc_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_allocation')
    op.drop_table('non_ac_room')
    op.drop_table('feedback')
    op.drop_table('chief_warden')
    op.drop_table('ac_room')
    op.drop_table('warden')
    op.drop_table('task_allocation')
    op.drop_table('room')
    op.drop_table('laundry')
    op.drop_table('equipment_usage')
    op.drop_table('complaint')
    op.drop_table('attendance')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_email'))

    op.drop_table('student')
    with op.batch_alter_table('staff_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_members_email'))

    op.drop_table('staff_members')
    op.drop_table('hostel')
    op.drop_table('gaming_facilities')
    # ### end Alembic commands ###
